Repository googleforgames/open-match, pull requests merged in 2021-04, with the labels that each got.

#1367 Sentinel fix
  go.sum
  install/helm/open-match/values.yaml
  third_party/swaggerui/config.json
Labels: cla: yes

#1368 Revert "Sentinel fix"
  go.sum
  install/helm/open-match/values.yaml
  third_party/swaggerui/config.json
Labels: cla: yes

#1369 Sentinel fix (2)
  go.sum
  install/helm/open-match/values.yaml
Labels: cla: yes

#1339 Add backfill scenario to scale tests
  Makefile
  examples/scale/backend/backend.go
  examples/scale/frontend/frontend.go
  examples/scale/scenarios/backfill/backfill.go
  examples/scale/scenarios/battleroyal/battleroyal.go
  examples/scale/scenarios/firstmatch/firstmatch.go
  examples/scale/scenarios/scenarios.go
  examples/scale/scenarios/teamshooter/teamshooter.go
  install/helm/open-match/subcharts/open-match-scale/dashboards/scale-test.json
Labels: area/testing, cla: yes

#1375 add mode to profile name for range of game modes
  tutorials/matchmaker101/solution/director/profile.go
Labels: area/developer-experience, area/refinement, cla: yes, good first issue

#1380 add andrewgrundy as codeowner
  .github/CODEOWNERS
Labels: cla: yes

#1379 Release 1.2.0
  Makefile
  cloudbuild.yaml
  go.mod
  go.sum
  install/helm/open-match/Chart.yaml
  install/helm/open-match/values.yaml
  third_party/swaggerui/config.json
  tutorials/matchmaker101/solution/director/profile.go
Labels: cla: yes
