Repository googleforgames/open-match, pull requests merged in 2022-06, with the labels that each got.

#1455 Update bugreport.md
  .github/ISSUE_TEMPLATE/bugreport.md
Labels: area/docs

#1462 update telemetry helm chart versions and gke version
  Makefile
  install/helm/open-match/subcharts/open-match-telemetry/Chart.yaml
  install/helm/open-match/subcharts/open-match-telemetry/charts/grafana-3.5.7.tgz
  install/helm/open-match/subcharts/open-match-telemetry/charts/grafana-6.29.3.tgz
  install/helm/open-match/subcharts/open-match-telemetry/charts/jaeger-0.13.3.tgz
  install/helm/open-match/subcharts/open-match-telemetry/charts/jaeger-0.56.5.tgz
  install/helm/open-match/subcharts/open-match-telemetry/charts/prometheus-15.8.7.tgz
  install/helm/open-match/subcharts/open-match-telemetry/charts/prometheus-8.14.0.tgz
  install/helm/open-match/subcharts/open-match-telemetry/templates/default-grafana-dashboards.yaml
Labels: kind/bug, area/refinement

#1465 Set default value of assignedDeleteTimeout
  internal/statestore/ticket.go
Labels: kind/bug
